name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        mkdir -p /home/runner/go/
        mv cwiczenie3 /home/runner/go/
        cd /home/runner/go/cwiczenie3 && go mod download
        go build /home/runner/go/cwiczenie3/main.go
